DROP DATABASE IF EXISTS db_crs;
CREATE DATABASE db_crs;
USE db_crs;

DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS FleetManager;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Roles;

CREATE TABLE Roles (
    RoleID INT PRIMARY KEY,
    RoleName VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    RoleID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL, 
    FailedAttempts INT DEFAULT 0,
    IsLocked BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (RoleID) REFERENCES Roles(RoleID) ON DELETE RESTRICT
);

CREATE TABLE Admin (
    AdminID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE FleetManager (
    ManagerID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    CompanyName VARCHAR(50) NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Customer (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);
CREATE TABLE Vehicle (
    VehicleID INT PRIMARY KEY AUTO_INCREMENT,
    ManagerID INT NOT NULL,
    Brand VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Location VARCHAR(100) NOT NULL,
    FuelType VARCHAR(20) NOT NULL,
    Transmission VARCHAR(20) NOT NULL,
    Seats INT NOT NULL,
    DailyPrice DECIMAL(10,2) NOT NULL CHECK (DailyPrice >= 0),
    StockQuantity INT NOT NULL CHECK (StockQuantity >= 0),
    Category ENUM('Sedan', 'SUV', 'Hatchback', 'Luxury', 'Economy') NOT NULL DEFAULT 'Economy',
    Status ENUM('Available', 'Unavailable', 'Archived') NOT NULL DEFAULT 'Available',
    Features TEXT,
    FOREIGN KEY (ManagerID) REFERENCES FleetManager(ManagerID) ON DELETE CASCADE
);

CREATE TABLE Reservation (
    ReservationID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT NOT NULL,
    VehicleID INT NOT NULL,
    PickupDate DATE NOT NULL,
    ReturnDate DATE NOT NULL,
    TotalPrice DECIMAL(10,2) NOT NULL,
    Status ENUM('Pending', 'Approved', 'Rejected', 'Canceled', 'Completed') NOT NULL DEFAULT 'Pending',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE RESTRICT,
    FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID) ON DELETE RESTRICT
);

CREATE TABLE Payment (
    PaymentID INT PRIMARY KEY AUTO_INCREMENT,
    ReservationID INT NOT NULL UNIQUE,
    Amount DECIMAL(10,2) NOT NULL CHECK (Amount > 0),
    PaymentMethod ENUM('credit_card', 'installment') NOT NULL,
    Status ENUM('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'completed',
    PaymentDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID) ON DELETE CASCADE
);

CREATE TABLE Review (
    ReviewID INT PRIMARY KEY AUTO_INCREMENT,
    VehicleID INT NOT NULL,
    CustomerID INT NOT NULL,
    Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Comment TEXT,
    ReviewDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID) ON DELETE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
);
