DROP DATABASE IF EXISTS db_crs;
CREATE DATABASE db_crs;
USE db_crs;

DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS FleetManager;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Roles;

CREATE TABLE Roles (
    RoleID INT PRIMARY KEY,
    RoleName VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE User (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    RoleID INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL, 
    FailedAttempts INT DEFAULT 0,
    IsLocked BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (RoleID) REFERENCES Roles(RoleID) ON DELETE RESTRICT
);